[tools]
cocogitto = "latest"
gitleaks = "latest"
node = "lts"
perl = "latest"
rust = { version = "latest", profile = "default", components = "rust-src,llvm-tools", targets = "wasm32-unknown-unknown,x86_64-unknown-linux-gnu" }
task = "latest"
yarn = "latest"
yq = "latest"

[env]
MISE_NODE_COREPACK = "true"
