[tools]
cocogitto = "latest"
copilot = "latest"
gitleaks = "latest"
node = "lts"
opengrep = "latest"
perl = "latest"
pnpm = "latest"
rust = { version = "latest", profile = "default", components = "rust-src,llvm-tools", targets = "wasm32-unknown-unknown,x86_64-unknown-linux-gnu" }
task = "latest"
uv = "latest"
yarn = "latest"
yq = "latest"

[env]
MISE_NODE_COREPACK = "true"

[hooks]
# Enabling corepack will install the `pnpm` package manager specified in your package.json
# alternatively, you can also install `pnpm` with mise
postinstall = 'npx corepack enable'

[settings]
# This must be enabled to make the hooks work
experimental = true
