version: "3"

tasks:
  init:
    desc: "Initialize the project"
    silent: true
    cmds:
      - echo "Initializing the project"
      - mise install
      - cargo install trunk ui-cli leptosfmt
      - cargo install cargo-leptos --locked
      - cog install-hook -a -o

  lint:
    desc: "Run linters and formatters"
    cmds:
      - echo "Running linters and formatters"
      - cargo fmt --all -- --check
      - cargo clippy --all-targets -- -D warnings

  test:
    desc: "Run all unit tests (excluding frontend WASM)"
    cmds:
      - cargo test --workspace --exclude frontend

  check:
    desc: "Check compilation for all targets"
    cmds:
      - cargo check --workspace --exclude frontend
      - cargo check --package frontend --features ssr
      - cargo check --package frontend --features hydrate --target
        wasm32-unknown-unknown

  build:
    desc: "Build the server binary (SSR)"
    cmds:
      - cargo build --package frontend --features ssr

  gen:
    desc: "Generate the content database and the sidebar data"
    deps:
      - gen:shiki
      - gen:content

  gen:shiki:
    desc: "Generate shiki import content"
    cmds:
      - pnpm run langs:codeblock && pnpm run build:shiki
  gen:content:
    desc: "Generate only the content database and sidebar data"
    cmds:
      - rm -rf ./target/content-build
      - cargo run --package content --bin content-build
      - cargo run --package content --bin generate-signature -- --output
        ./target/content-build/public/minia/signature.png

  dev:
    desc: "Start development server with hot-reloading (requires cargo-leptos)"
    cmds:
      - cargo leptos watch --project frontend
