[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[package.metadata.leptos]
# Name used by cargo-leptos
name = "monofolio"
# Output directory for the WASM artefacts
site-root = "target/site"
# Public assets directory
site-pkg-dir = "pkg"
# Assets directory (images, CSS, etc.)
assets-dir = "public"
# JS entry point created by cargo-leptos
js-dir = "js"
# The app binary
bin-exe-name = "frontend"
# Feature flags
lib-features = ["hydrate"]
bin-features = ["ssr"]
# Styles
style-file = "../../target/tmp/tailwind.css"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "frontend"
path = "src/main.rs"

[dependencies]
actix-files = { workspace = true, optional = true }
actix-web = { workspace = true, optional = true }
anyhow = { workspace = true, optional = true }
console_error_panic_hook = { version = "0.1", optional = true }
futures = { version = "0.3.32", optional = true }
gloo-net = { version = "0.7", features = ["http"], optional = true }
js-sys = { version = "0.3", optional = true }
leptos = { workspace = true }
leptos_actix = { workspace = true, optional = true }
leptos_meta = { workspace = true }
leptos_router = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
tracing = { workspace = true }
tracing-actix-web = { workspace = true, optional = true }
utoipa = { workspace = true, optional = true }
utoipa-actix-web = { workspace = true, optional = true }
utoipa-scalar = { workspace = true, optional = true }
wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
web-sys = {
  version = "0.3",
  features = [
    "CanvasRenderingContext2d",
    "Clipboard",
    "EventTarget",
    "HtmlCanvasElement",
    "KeyboardEvent",
    "MouseEvent",
    "Navigator",
    "Storage",
    "Touch",
    "TouchEvent",
    "TouchList",
    "Window",
  ],
  optional = true
}

api = { path = "../../libs/api", optional = true }
content = { path = "../../libs/content" }
icondata_si = "0.1"
icons.workspace = true
leptos_icons = "0.7"
leptos_ui.workspace = true
trace = { path = "../../libs/trace", features = ["otel"], optional = true }
tw_merge.workspace = true

[features]
default = ["ssr"]
hydrate = [
  "dep:console_error_panic_hook",
  "dep:futures",
  "dep:gloo-net",
  "dep:js-sys",
  "dep:wasm-bindgen",
  "dep:wasm-bindgen-futures",
  "dep:web-sys",
  "leptos/hydrate",
]
ssr = [
  "dep:actix-files",
  "dep:actix-web",
  "dep:anyhow",
  "dep:api",
  "dep:leptos_actix",
  "dep:serde_yaml",
  "dep:tokio",
  "dep:trace",
  "dep:tracing-actix-web",
  "dep:utoipa",
  "dep:utoipa-actix-web",
  "dep:utoipa-scalar",
  "leptos_meta/ssr",
  "leptos_router/ssr",
  "leptos/ssr",
]
