import { createHighlighterCore } from "shiki/core";
import { createJavaScriptRegexEngine } from "shiki/engine/javascript";
import themeVitesseDark from "@shikijs/themes/vitesse-dark";

// @shiki-lang-imports-start — auto-generated by scripts/list-codeblock-langs.mjs, do not edit manually
import langBash from "@shikijs/langs/bash";
import langCpp from "@shikijs/langs/cpp";
import langCsharp from "@shikijs/langs/csharp";
import langGo from "@shikijs/langs/go";
import langJava from "@shikijs/langs/java";
import langJavascript from "@shikijs/langs/javascript";
import langJsx from "@shikijs/langs/jsx";
import langPhp from "@shikijs/langs/php";
import langPython from "@shikijs/langs/python";
import langRust from "@shikijs/langs/rust";
import langSh from "@shikijs/langs/sh";
import langSvelte from "@shikijs/langs/svelte";
import langTypescript from "@shikijs/langs/typescript";
import langVue from "@shikijs/langs/vue";
// @shiki-lang-imports-end

// @shiki-langs-start — auto-generated by scripts/list-codeblock-langs.mjs, do not edit manually
const LANGS = [langBash, langCpp, langCsharp, langGo, langJava, langJavascript, langJsx, langPhp, langPython, langRust, langSh, langSvelte, langTypescript, langVue];
// @shiki-langs-end

const THEME = "vitesse-dark";

let highlighterPromise;

function getHighlighter() {
  if (!highlighterPromise) {
    highlighterPromise = createHighlighterCore({
      themes: [themeVitesseDark],
      langs: LANGS,
      engine: createJavaScriptRegexEngine(),
    });
  }
  return highlighterPromise;
}

window.__mfHighlightCode = async function __mfHighlightCode(preEl, language) {
  if (!preEl) return false;

  const highlighter = await getHighlighter();
  const source = preEl.textContent || "";
  const lang = (language || preEl.dataset.language || "bash").toLowerCase();

  let html;
  try {
    html = highlighter.codeToHtml(source, { lang, theme: THEME });
  } catch (_) {
    // Unknown language: render as plain text without syntax highlighting
    html = `<pre><code>${source.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")}</code></pre>`;
  }

  const wrapper = document.createElement("div");
  wrapper.innerHTML = html;
  const shikiPre = wrapper.querySelector("pre");
  if (!shikiPre) return false;

  shikiPre.classList.add(
    "mb-0",
    "rounded-b-lg",
    "overflow-x-auto",
    "border",
    "border-border",
  );
  const code = shikiPre.querySelector("code");
  if (code) {
    code.classList.add("text-sm");
  }

  preEl.replaceWith(shikiPre);
  return true;
};
