name: Container Build

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.rs"
      - "**/*.css"
      - "**/*.js"
      - "**/*.toml"
      - "**/*.yaml"
      - "**/*.json"
      - "Cargo.lock"
      - ".dockerignore"
      - "apps/frontend/public/**"
      - "contents/**"
      - "Containerfile"
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
    paths:
      - "**/*.rs"
      - "**/*.css"
      - "**/*.js"
      - "**/*.toml"
      - "**/*.yaml"
      - "**/*.json"
      - "Cargo.lock"
      - ".dockerignore"
      - "apps/frontend/public/**"
      - "contents/**"
      - "Containerfile"
  workflow_dispatch:
  schedule:
    - cron: "50 23 * * *"

permissions:
  contents: read

env:
  REGISTRY: registry.batleforc.fr

jobs:
  build:
    name: Build container images
    runs-on: buildah
    strategy:
      matrix:
        include:
          - name: "Backend Container"
            context: .
            dockerfile: Containerfile
            image_name: ${{ github.repository_owner }}/monofolio-rs
    permissions:
      contents: read
      id-token: write
    outputs:
      image_backend: ${{ env.REGISTRY }}/${{ github.repository_owner
        }}/monofolio-rs:${{ github.sha }}
    steps:
      - uses: https://git.batleforc.fr/action/checkout@v6
      - name: Create env var with vault CA certificate
        id: cert
        run: echo "VAULT_CA_CERTIFICATE=$(cat "$VAULT_CA_CERT" | base64 -w 0)">>
          "$GITHUB_OUTPUT"
      - name: Get env variables from vault
        uses: https://git.batleforc.fr/action/hashicorp_vault-action@v3
        with:
          url: https://vault.vault:8200
          caCertificate: ${{ steps.cert.outputs.VAULT_CA_CERTIFICATE }}
          method: jwt
          role: forgejo_default_policy
          jwtGithubAudience: forgejo_action
          secrets: |
            git-vault/data/batleforc/monofolio-rs username | REGISTRY_USER ;
            git-vault/data/batleforc/monofolio-rs password | REGISTRY_PAT ;

      - run: buildah login --username ${{ secrets.REGISTRY_USER }} --password ${{
          secrets.REGISTRY_PAT }} ${{ env.REGISTRY }}
      - name: Build Image
        run: |
          IMAGE_TAG="${{ env.REGISTRY }}/${{ matrix.image_name }}:${GITHUB_SHA}"
          IMAGE_TAG_BRANCH="${{ env.REGISTRY }}/${{ matrix.image_name }}:${GITHUB_REF_NAME}"
          CACHE_SCOPE_MAIN="monofolio-rs-container-main"
          CACHE_SCOPE_REF="monofolio-rs-container-${GITHUB_REF_NAME//\//-}"
          buildah build  \
            --platform linux/amd64 \
            --cache-from type=gha,scope=$CACHE_SCOPE_MAIN \
            --cache-from type=gha,scope=$CACHE_SCOPE_REF \
            --cache-to type=gha,scope=$CACHE_SCOPE_REF,mode=max \
            --tag $IMAGE_TAG \
            --tag $IMAGE_TAG_BRANCH \
            --file ${{ matrix.dockerfile }} \
            --push ${{ matrix.context }}
