name: Container Build

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.rs"
      - "**/*.css"
      - "**/*.js"
      - "**/*.toml"
      - "**/*.yaml"
      - "**/*.json"
      - "Cargo.lock"
      - ".dockerignore"
      - "apps/frontend/public/**"
      - "contents/**"
      - "Containerfile"
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
    paths:
      - "**/*.rs"
      - "**/*.css"
      - "**/*.js"
      - "**/*.toml"
      - "**/*.yaml"
      - "**/*.json"
      - "Cargo.lock"
      - ".dockerignore"
      - "apps/frontend/public/**"
      - "contents/**"
      - "Containerfile"
  workflow_dispatch:
  schedule:
    - cron: "50 23 * * *"

permissions:
  contents: read

env:
  REGISTRY: registry.batleforc.fr

concurrency:
  # only run one build at a time
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build container images
    enable-openid-connect: true # Required for vault authentication
    runs-on: buildah
    strategy:
      matrix:
        include:
          - name: "Backend Container"
            context: .
            dockerfile: Containerfile
            image_name: batleforc/monofolio-rs
    permissions:
      contents: read
      id-token: write
    outputs:
      image_backend: ${{ env.REGISTRY }}/${{ github.repository_owner
        }}/monofolio-rs:${{ github.sha }}
    steps:
      - uses: https://git.batleforc.fr/action/checkout@v6
      - name: Setup ArgoCD CLI
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          mkdir -p "$RUNNER_TEMP/argocd"
          install -m 555 argocd-linux-amd64 "$RUNNER_TEMP/argocd/argocd"
          rm argocd-linux-amd64
          echo "$RUNNER_TEMP/argocd" >> "$GITHUB_PATH"
      - name: Create env var with vault CA certificate
        id: cert
        run: echo "VAULT_CA_CERTIFICATE=$(cat "$VAULT_CA_CERT" | base64 -w 0)">>
          "$GITHUB_OUTPUT"
      - name: Get env variables from vault
        uses: https://git.batleforc.fr/action/hashicorp_vault-action@v3
        id: vault
        with:
          url: https://vault.vault:8200
          caCertificate: ${{ steps.cert.outputs.VAULT_CA_CERTIFICATE }}
          method: jwt
          path: forgejo_jwt
          role: forgejo_action
          jwtGithubAudience: forgejo_action
          secrets: |
            git-vault/data/batleforc/monofolio-rs/registry username | REGISTRY_USER ;
            git-vault/data/batleforc/monofolio-rs/registry password | REGISTRY_PAT ;
            git-vault/data/batleforc/monofolio-rs/registry url | REGISTRY ;

      - run: buildah login --username ${{ steps.vault.outputs.REGISTRY_USER }}
          --password ${{ steps.vault.outputs.REGISTRY_PAT }} ${{
          steps.vault.outputs.REGISTRY }}
      - name: Build Image
        run: |
          IMAGE_TAG="${{ env.REGISTRY }}/${{ matrix.image_name }}:${GITHUB_SHA}"
          IMAGE_TAG_BRANCH="${{ env.REGISTRY }}/${{ matrix.image_name }}:${GITHUB_REF_NAME}"
          buildah build  \
            --platform linux/amd64 \
            --cache-to=${{ env.REGISTRY }}/${{ matrix.image_name }} \
            --cache-from=${{ env.REGISTRY }}/${{ matrix.image_name }} \
            --tag $IMAGE_TAG \
            --tag $IMAGE_TAG_BRANCH \
            --file ${{ matrix.dockerfile }} \
            ${{ matrix.context }}
          buildah push $IMAGE_TAG
          buildah push $IMAGE_TAG_BRANCH
      - name: Obtain access Token
        id: idtoken
        run: |
          TOKEN_ANSWER=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL")

          FORGEJO_ID_TOKEN=$(echo $TOKEN_ANSWER | jq -r .value)

          DEX_URL="https://argo.batleforc.fr/api/dex/token"
          echo "Exchanging Forgejo ID Token for ArgoCD access token..."
          DEX_TOKEN_RESPONSE=$(curl -sSf \
              "$DEX_URL" \
              --user argo-cd-cli: \
              --data-urlencode "connector_id=forgejo-actions" \
              --data-urlencode "grant_type=urn:ietf:params:oauth:grant-type:token-exchange" \
              --data-urlencode "scope=openid email profile federated:id" \
              --data-urlencode "requested_token_type=urn:ietf:params:oauth:token-type:access_token" \
              --data-urlencode "subject_token=$FORGEJO_ID_TOKEN" \
              --data-urlencode "subject_token_type=urn:ietf:params:oauth:token-type:id_token")
          DEX_TOKEN=$(jq -r .access_token <<< $DEX_TOKEN_RESPONSE)

          if [[ -z "$DEX_TOKEN" ]]; then
            echo "::error::No token found in dex response"
            exit 1
          fi

          echo "::add-mask::$(echo "$DEX_TOKEN" | base64 -w0)"
          echo "::add-mask::$DEX_TOKEN"
          echo "dex-token=$DEX_TOKEN" >> "$GITHUB_OUTPUT"
      - name: Refresh ArgoCD Application
        env:
          ARGOCD_AUTH_TOKEN: ${{ steps.idtoken.outputs.dex-token }}
          ARGOCD_SERVER: argo.batleforc.fr
          ARGOCD_OPTS: --grpc-web
        run: |
          set -x
          argocd app sync monofolio-rs --timeout 300
